spring.profiles.active=prod

db.driver=com.mysql.cj.jdbc.Driver
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
db.pool.maximum-pool-size=${DB_POOL_MAXIMUM_POOL_SIZE:20}

jwt.secret=${JWT_SECRET}
jwt.access-token-validity-ms=${JWT_ACCESS_TOKEN_VALIDITY_MS:900000}
jwt.refresh-token-validity-ms=${JWT_REFRESH_TOKEN_VALIDITY_MS:1209600000}

redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT:6379}
